support for backblaze/s3, support for mounting local repos

diff --git a/resticw b/resticw
--- a/resticw
+++ b/resticw
@@ -11,35 +11,18 @@ config_list="all|$(IFS='|' ; echo -e "${CONFIGS[*]}")"
 
 # As the 'backup' user:
 # - the config must be owned by root
-# - the cache dir is /var/cache/restic
-# (The default RESTIC_CACHE_DIR is $XDG_CACHE_HOME/restic,
-#  or ~/.cache/restic if XDG_CACHE_HOME is not set.)
 uid=$UID
 [ "x$UID" == "x$(id -u backup)" ] && uid=0
-[ "x$uid" == "x0" ] && export RESTIC_CACHE_DIR=/var/cache/restic
-if [ "x$UID" == "x0" ]; then
-    mkdir -p -m 750 "$RESTIC_CACHE_DIR"
-    chown backup:backup "$RESTIC_CACHE_DIR"
-
-    PRIV=-all,+dac_read_search  # the 'backup' user needs 'root' read-only access
-    exec setpriv --reuid backup --regid backup --clear-groups --reset-env \
-        --bounding-set=${PRIV} --inh-caps=${PRIV} --ambient-caps=${PRIV} \
-        --no-new-privs \
-        -- $0 "$@"
-fi
-# check permissions are "safe"
-#id && setpriv --dump
 
 TARGET="${1//[^a-zA-Z0-9-]/}" # only accept alphanumerics
 [ "$TARGET" != "$1" ] && echo "error: $1: invalid target" 1>&2 && exit 1
 shift
-
 if [ "x$TARGET" == "xall" ]; then
-  [[ ! "$@" =~ (--quiet) ]] && set -e
-  for i in ${CONFIGS[@]}; do
-    "$0" "$i" $@
-  done
-  exit 0
+    [[ ! "$@" =~ (--quiet) ]] && set -x
+    for i in ${CONFIGS[@]}; do
+        "$0" "$i" $@
+    done
+    exit 0
 fi
 
 # $HOME/.config/resticw superceeds /etc/resticw config
@@ -48,25 +31,48 @@ for i in "/etc/resticw/$TARGET" "$HOME/.config/resticw/$TARGET"; do
     [ -d "$i" ] && DIR="$i"
 done
 [ ! -d "$DIR" ] && echo "error: $TARGET: not a valid config dir" 1>&2 && exit 1
-[ "x$(stat -c '%u:%a' "$DIR")" != "x$uid:755" ] && echo "error: '$DIR' permissions must be 755 and owned by ($uid)" 1>&2 && exit 1
-
+[ "x$(stat -c '%u:%a' "$DIR")" != "x$uid:755" ] && echo "error: '$DIR' permissions must be 755 and owned by $(id -un $uid) ($uid)" 1>&2 && exit 1
 # required config files
 for i in passwd repo; do
     [ ! -f "$DIR/$i" ] && echo "error: $DIR/$i: missing" 1>&2 && exit 1
 done
 # check ownership and permissions
-for f in passwd repo backup exclude hook retention; do
+for f in passwd repo backup exclude hook retention env mount; do
     [ ! -f "$DIR/$f" ] && continue
     ff="$(realpath "$DIR/$f")"
-    [ "x$(stat -c '%u' "$ff")" != "x$uid" ] && echo "error: $DIR/$f not owned by user ($uid)" 1>&2 && exit 1
+    [ "x$(stat -c '%u' "$ff")" != "x$uid" ] && echo "error: $DIR/$f not owned by $(id -un $uid) ($uid)" 1>&2 && exit 1
     case "$f" in
         passwd) mod="600";;
+        env) mod="700";;
         hook) mod="750";;
         *) mod="644" ;;
     esac
     [ "x$(stat -c '%a' "$ff")" != "x$mod" ] && echo "error: $DIR/$f permissions must be $mod" 1>&2 && exit 1
     [ $f == "hook" ] && [ ! -x "$DIR/hook" ] && echo "error: $DIR/$f not executable by user '$USER' ($UID)" 1>&2 && exit 1
 done
+
+# As the 'backup' user:
+# - the cache dir is /var/cache/restic
+# (The default RESTIC_CACHE_DIR is $XDG_CACHE_HOME/restic,
+#  or ~/.cache/restic if XDG_CACHE_HOME is not set.)
+[ "x$uid" == "x0" ] && export RESTIC_CACHE_DIR=/var/cache/restic
+if [ "x$UID" == "x0" ]; then
+    mkdir -p -m 750 "$RESTIC_CACHE_DIR"
+    chown backup:backup "$RESTIC_CACHE_DIR"
+
+    mnt="$(cat $DIR/mount 2>/dev/null)"
+    [ -n "$mnt" ] && mount "$mnt" && trap 'umount "$mnt"' EXIT
+
+    set -e
+    PRIV=-all,+dac_read_search  # the 'backup' user needs 'root' read-only access
+    setpriv --reuid backup --regid backup --clear-groups --reset-env \
+        --bounding-set=${PRIV} --inh-caps=${PRIV} --ambient-caps=${PRIV} \
+        --no-new-privs \
+        -- $0 "$TARGET" "$@"
+    exit $?
+fi
+# check permissions are "safe"
+#id && setpriv --dump
 
 rotate=()
 if [ -f "$DIR/retention" ]; then
@@ -99,14 +105,20 @@ case "$CMD" in
             EXEC+=" && $RESTIC forget $repo ${rotate[@]} --prune"
             [[ "$@" =~ (--quiet) ]] && EXEC+=" --quiet" # 'forget' should go quiet too
         fi
-	;;
+        ;;
     ncdu) EXEC="${RESTIC} --no-lock $repo $@ ls latest --ncdu | ${NCDU} -f -";;
     redu) EXEC="${REDU} -j 12 $repo $@";;
     *) EXEC="$RESTIC $repo $CMD $@";;
 esac
-[ -f "$DIR/hook" ] && EXEC="$DIR/hook before $CMD && $EXEC && $DIR/hook after $CMD"
+[ -f "$DIR/hook" ] && EXEC="$DIR/hook before $CMD && trap \"$DIR/hook after $CMD\" EXIT && $EXEC"
 
 [[ "$@" =~ (--dry-run|--pretend) ]] && echo "$EXEC" && exit 0
+
+if [ -f "$DIR/env" ]; then
+    set -a
+    source "$DIR/env"
+    set +a
+fi
 
 set -e -o pipefail
 [[ ! "$@" =~ (--quiet) ]] && set -x
